server:
  port: 8084
  # Configuración de servlet para asegurar codificación correcta en las respuestas
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: mscics-integrationhub

  # --- CONFIGURACIÓN DE PERSISTENCIA (ORACLE 11G) ---
  datasource:
    #url: ${DB_URL:jdbc:oracle:thin:@172.16.8.166:1630:BDTU2}
    #username: ${DB_USER:MGDBI_USER}
    #password: ${DB_PASSWORD:BUZON9}
    #driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL:jdbc:mariadb://localhost:3306/:1630:dbcics}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Admin1234}
    driver-class-name: org.mariadb.jdbc.Driver
    # Pool de conexiones Hikari (Ajustado para alta concurrencia) 
    hikari:
      pool-name: HikariPool-CICS-Hub
      maximum-pool-size: 60
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # --- CONFIGURACIÓN DE HIBERNATE / JPA ---
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.OracleDialect
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          # Necesario para el manejo de CLOB (Error logs) en Oracle
          lob:
            non_contextual_creation: true
        # Estrategia de nombrado para Spring Boot 3 / Hibernate 6
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# --- SEGURIDAD PERIMETRAL (JWT) ---
jwt:
  # Clave secreta (Base64). Se recomienda rotar cada 90 días.
  secret: ${JWT_SECRET:TExBVkVfTVVZX1NFQ1JFVEzE3Zmxu7BSGSJx72BSBXM}
  # Tiempo de vida del token (10 horas)
  expiration: 36000000

# --- MONITOREO Y SALUD (ACTUATOR) ---
info:
  app:
    name: ${spring.application.name}
    description: "CICS Integration Hub"
    version: "1.0.0"        # Versión de Negocio  
    api-version: "1.0.0"   # Versión técnica de la API
    status: "Production"
management:
  info:
    env:
      enabled: true # IMPORTANTE: En Spring Boot 3 debe habilitarse explícitamente
  endpoints:
    web:
      base-path: /mscics-integrationhub/v1/actuator
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

# --- CONFIGURACIÓN IBM CICS TRANSACTION GATEWAY (CTG) ---
ctg:
  ipaddress: tcp://10.100.68.200
  port: 1425
  servername: CICSIPIC

 

# --- PARÁMETROS DEL MICROSERVICIO ---
app:
  cics:
    # Pool de hilos para procesamiento asíncrono y concurrente
    thread-pool-size: 100
    
    # Configuración del Pool de objetos JavaGateway (CTG)
    # IMPORTANTE: Mantener coherencia con la capacidad del servidor CICS
    pool:
      max-total: 200          # Máximo de conexiones físicas abiertas
      max-idle: 50           # Mantener conexiones 
      min-idle: 20            # Mínimo de conexiones siempre listas
      max-wait-millis: 3000  # Tiempo de espera antes de error por saturación
      
    # Mantenimiento preventivo del pool
    eviction:
      time-between-runs-seconds: 10
      min-evictable-idle-minutes: 1 # Si una conexión está ociosa 1 min, liberarla

# --- LOGGING ---
logging:
  level:
    root: INFO
    mx.gob.imss.cics: DEBUG
    org.springframework.security: INFO