server:
  port: 8084

jwt:
  secret: TExBVkVfTVVZX1NFQ1JFVEzE3Zmxu7BSGSJx72BSBXM

spring:
  application:
    name: mscics-canales

management:
  endpoints:
    web:
      base-path: /mscics-canales/v1/actuator
      exposure:
        include: health
  endpoint:
    auditevents:
      enabled: true

# Configuración del servidor CTG
ctg:
  ipaddress: tcp://10.100.68.137
  port: 1425
  servername: CICSIPIC

# Configuración de versión
ea01:
  version: 03.03

app:
  cics:
    # Número máximo de hilos simultáneos para procesar Datos
    thread-pool-size: 10

    # Ejemplo de valores predeterminados para CICS
    default-cics-user: PEMI091
    default-cics-password: MOR2603
    default-cics-programa: EGHLA050
    default-cics-transaccion: GH50

    # Configuración del pool CTG
    pool:
      max-total: 10          # Número máximo de conexiones CTG en el pool
      max-idle: 10           # Número máximo de conexiones CTG inactivas
      min-idle: 5           # Número mínimo de conexiones CTG inactivas
      max-wait-millis: 5000  # Tiempo máximo de espera para obtener una conexión


    default-rest-user: jaime
    default-rest-password: imss1234