# ***
# * Archivo para la configuraci�n de par�metros de la aplicaci�n
# ***

# ***
# * Transacci�n CICS EA01
# ***

# Versi�n del Sistema
EA01.version = 03.03
 
# Direccion IP del Servidor CTG
#ctg.ipaddress = tcp\://11.254.171.200
ctg.ipaddress = tcp\://10.100.68.200
#ctg.ipaddress = tcp\://11.254.13.162
# Puerto usado para Conexion a Servidor CTG
ctg.port =1425
# ctg.port =2006
# Nombre del servidor CICS
ctg.servername = CICSIPIC
#ctg.servername = IPIC
# ctg.servername = IMSSREG1
# N�mero de creditos contenidos por cadena de retorno para la Consulta de Estado de Cuenta
estadoCuenta.creditosPorCadena =4