# ***
# * Archivo para la configuración de parámetros de la aplicación
# ***

# ***
# * Transacción CICS EA01
# ***

# Versión del Sistema
EA01.version = 03.03
# Conexión con el webService
serviceCon = http\://localhost\:9080/cobranza/services/PlainTransaction
# Direccion IP del Servidor CTG
#ctg.ipaddress = tcp\://11.254.171.200
ctg.ipaddress = tcp\://10.100.68.200
#ctg.ipaddress = tcp\://11.254.13.162
# Puerto usado para Conexion a Servidor CTG
ctg.port =1425
# ctg.port =2006
# Nombre del servidor CICS
ctg.servername = CICSIPIC
#ctg.servername = IPIC
# ctg.servername = IMSSREG1
# Número de creditos contenidos por cadena de retorno para la Consulta de Estado de Cuenta
estadoCuenta.creditosPorCadena =4